"""
Build a very basic gallery
"""


from pathlib import Path

print("_________")
print(" Gallery ")
print("_________")

print(':: auto-generated by gal.py')
p = Path()
for image in p.glob('images/*.png'):
    print(f'.. image:: {image}')
    print
